moviesite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls')),
    path('admin/', admin.site.urls),
]

posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'
urlpatterns = [
    path('', views.ListView.as_view(), name='index'),
    path('create/', views.CreateView, name='create'),
    path('categories/', views.ListCategoryView.as_view(), name='list_categories'),
    path('categories/<int:category_id>', views.DetailCategory, name='list_posts_per_category'),
    path('<int:post_id>/', views.DetailView, name='detail'),
    path('<int:post_id>/comment/',views.create_comment, name = 'comment'),
    path('update/<int:post_id>/', views.UpdateView, name='update'),
    path('delete/<int:post_id>/', views.DeleteView, name='delete'),
]

staticpages/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('about/', views.about, name='about'),
    path('', views.index, name='index'),
]

posts/models.py
from django.db import models
from django.conf import settings



class Post(models.Model):
    titulo = models.CharField(max_length=255)
    data = models.DateTimeField()
    conteudo = models.CharField(max_length=2000, null=True)

    def __str__(self):
        return f'{self.titulo} ({self.data}) \n {self.conteudo} '

class Comment(models.Model):
    autor = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE)
    texto = models.CharField(max_length=280)
    data = models.DateTimeField()	
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self):
        return f'"{self.texto}" - {self.autor}'


class Category(models.Model):
    nome = models.CharField(max_length=50)
    descrição = models.CharField(max_length=280)
    posts = models.ManyToManyField(Post)

    def __str__(self):
        return f'"{self.nome}" - {self.descrição}'

staticpages/models.py
from django.db import models

# Create your models here.

posts/forms.py
from django.forms import ModelForm
from .models import Post, Comment


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = [
            'titulo',
            'data',
            'conteudo',
        ]
        labels = {
            'titulo': 'Título',
            'data': 'Data de Postagem',
            'conteudo': 'Conteudo',
        }

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = [
            'autor',
            'texto',
            'data',
        ]
        labels = {
            'autor': 'AutorLabel',
            'texto': 'Comentário',
	        'data': 'data',
        }

posts/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render, get_object_or_404
from django.views import generic

from .models import Post, Comment,Category
from .forms import PostForm,CommentForm



#Views Genéricas
class ListView(generic.ListView):
    model = Post
    template_name = 'posts/index.html'
    #template_name = 'posts/listagem_de_categorias.html'

def DetailView(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    context = {'post': post}
    return render(request, 'posts/detail.html', context)


def CreateView(request):
    if request.method == 'POST':
        post_form = PostForm(request.POST)

        if post_form.is_valid():
            post = Post(**post_form.cleaned_data)
            post.save()
            
            return HttpResponseRedirect(
                reverse('posts:detail', args=(post.pk, )))
    else:
        post_form = PostForm()

    context = {'post_form': post_form}
    return render(request, 'posts/create.html', context)



def UpdateView(request, post_id):
    post = get_object_or_404(Post, pk=post_id)

    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post.titulo = form.cleaned_data['titulo']
            post.data = form.cleaned_data['data']
            post.conteudo = form.cleaned_data['conteudo']
            post.save()
            return HttpResponseRedirect(
                reverse('posts:detail', args=(post.id, )))
    else:
        form = PostForm(
            initial={
                'titulo': post.titulo,
                'data': post.data,
                'conteudo': post.conteudo
            })

    context = {'post': post, 'form': form}
    return render(request, 'posts/update.html', context)


def DeleteView(request, post_id):
    post = get_object_or_404(Post, pk=post_id)

    if request.method == "POST":
        post.delete()
        return HttpResponseRedirect(reverse('posts:index'))

    context = {'post': post}
    return render(request, 'posts/delete.html', context)

def create_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment_autor = form.cleaned_data['autor']
            comment_texto = form.cleaned_data['texto']
            comment_data  = form.cleaned_data['data']
            comment = Comment(autor=comment_autor,
                            texto=comment_texto,
                            data =  comment_data,
                            post=post)
            comment.save()
            return HttpResponseRedirect(
                reverse('posts:detail', args=(post_id, )))
    else:
        form = CommentForm()
    context = {'form': form, 'post': post}
    return render(request, 'posts/comment.html', context)



class ListCategoryView(generic.ListView):
    model = Category
    template_name = 'posts/listagem_de_categorias.html'

def DetailCategory(request, category_id):
    category = get_object_or_404(Category, pk=category_id)
    context = {'category': category}
    return render(request, 'posts/ListagemPostPorCategoria.html', context)

staticpages/views.py
from django.shortcuts import render


def index(request):
    context = {}
    return render(request, 'staticpages/index.html', context)


def about(request):
    context = {}
    return render(request, 'staticpages/about.html', context)

posts/templates/posts/ListagemPostPorCategoria.html
{% extends 'base.html' %}

{% block content %}
<h2>Categoria: "{{category.nome}}"</h2>
<h3>Descrição:</h3>
<p>{{category.descrição}}</p>

<h3>Lista de posts associados à categoria:<h3>
{% if category.posts.all %}
<section class="lista-de-cards">
    {% for post in category.posts.all %}
    <article class="card">
	<small>({{ post.data|date }})</small></br>
        <a href="{% url 'posts:detail' post.id %}">{{ post.titulo }}</a>
    </article>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhum post associado a essa categoria.</p>
{% endif %}

{% endblock content %}

posts/templates/posts/comment.html
{% extends 'base.html' %}

{% block content %}
<h2>Comentar Post {{ post.titulo }} ({{ post.data|date }})</h2>

<form action="{% url 'posts:comment' post.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Postar Resenha</button>
</form>

<form action="{% url 'posts:comment' post.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Postar Resenha</button>
</form>

<p><a href="{% url 'posts:detail' post.id %}">Voltar para a página do filme</a></p>
{% endblock content %}

posts/templates/posts/create.html
{% extends 'base.html' %}

{% block title %}
Criar novo Post
{% endblock title %}

{% block content %}
<h2>Adicionar Post</h2>

<form action="{% url 'posts:create' %}" method="post">
    {% csrf_token %}
    {{ post_form.as_p }}

    <button type="submit">Criar</button>
</form>

{% endblock content %}

posts/templates/posts/delete.html
{% extends 'base.html' %}

{% block content %}
<form action="{% url 'posts:delete' post.id %}" method="post">
    {% csrf_token %}
    <p>
        Você tem certeza que deseja apagar o post "{{ post.titulo }} ({{ post.data }})"?
    </p>
    <button type="submit">Apagar</button>
</form>

{% endblock content %}

posts/templates/posts/detail.html
{% extends 'base.html' %}

{% block title %}
{{ post.titulo }} ({{ post.data }}
{% endblock title %}

{% block content %}
<h2>Titulo: {{ post.titulo}}</h2>
<h5>postado em: ({{ post.data|date }}) </h5>


<section>
    <header>
        <h3>Categorias</h3>
    </header>
    <ul>
        {% if post.category_set.all %}
        {% for category in post.category_set.all %}
		<li>{{ category.nome }}</li>
        {% endfor %}
        {% else %}
        <p>Ainda não existe nenhuma categoria associada a esse post.</p>
        {% endif %}
    </ul>

    <hr>
</section>





<section class="dados-de-filme">

    <ul>


	{{ post.conteudo|safe }}
        <li><a href="{% url 'posts:update' post.id %}">Editar</a></li>
        <li><a href="{% url 'posts:delete' post.id %}">Apagar</a></li>
    </ul>
</section>

<hr>

<section>
    <header>
        <h3>Comentários</h3>
    </header>
    <ul>
        {% if post.comment_set.all %}
        {% for comment in post.comment_set.all|dictsort:"data" %}
        <figure>
            <blockquote>
                "{{ comment.texto }}"
            </blockquote>
            <figcaption>—{{ comment.autor }} ({{ comment.data|date }})
        </figure>
        {% endfor %}
        {% else %}
        <p>Ainda não existe nenhum comentário para esse filme.</p>
        {% endif %}
    </ul>

    <hr>

    <a href="{% url 'posts:comment' post.pk %}"><button>Publique um comentário para esse Post</button></a>
</section>


{% endblock content %}

posts/templates/posts/index.html
{% extends 'base.html' %}

{% block content %}
<h2>Todos os Posts</h2>

{% if post_list %}
<section class="lista-de-cards">
    {% for post in post_list %}
    <article class="card">
	<small>({{ post.data|date }})</small></br>
        <a href="{% url 'posts:detail' post.id %}">{{ post.titulo }}</a>
    </article>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhum filme.</p>
{% endif %}

{% endblock content %}

posts/templates/posts/listagem_de_categorias.html
{% extends 'base.html' %}

{% block content %}
<h2>Todos as categorias</h2>

{% if category_list %}
<section class="lista-de-cards">
    {% for category in category_list %}
    <article class="card">
	<b><a href="{% url 'posts:list_posts_per_category' category.id %}">{{ category.nome }}</a></b>
	<p>{{category.descrição}}</p>
	
    </article>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhum filme.</p>
{% endif %}


{% endblock content %}

posts/templates/posts/update.html
{% extends 'base.html' %}

{% block content %}
<h2>Atualizar Post "{{ post.titulo }}" ({{ post.data}})</h2>
<form method="POST" action="{% url 'posts:update' post.id%}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Atualizar</button>
</form>

{% endblock content %}

staticpages/templates/staticpages/about.html
{% extends 'base.html' %}

{% block title %}
Sobre
{% endblock title %}

{% block content %}
<h2>Sobre este site</h2>
{% endblock content %}

staticpages/templates/staticpages/index.html
{% extends 'base.html' %}

{% block title %}
Página Inicial
{% endblock title %}

{% block content %}
<h1><i>Watch that film!</i></h1>
<p>A Página para Comunidade Resenhadora de Filmes</p>
{% endblock content %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}{% endblock %} | Meu Blog
    </title>
    <link href="https://fonts.googleapis.com/css?family=Inter&display=swap" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
</head>

<body>
    <header id="cabecalho-principal">
        <a href="{% url 'posts:index' %}"> <img src="{% static 'logo.png' %}"> </a>
        <nav id="navegacao-principal">
            <ul>	
                <li><a href="{% url 'posts:index' %}">Lista de Todos os Posts</a></li>
                <li><a href="{% url 'posts:create' %}">Criar Post</a></li>
		<li><a href="{% url 'posts:list_categories' %}">Categorias</a></li>

            </ul>
        </nav>

    </header>
    <main id="conteiner-principal">
        {% block content %}
        {% endblock content %}
    </main>
    <footer id="rodape-principal">
        <p>
            <small>Copyright 2021</small>
        </p>
    </footer>
</body>

</html>